table RiesgoPorHora
	lineageTag: aaaaaaaa-0000-0000-0000-000000000200

	column dispositivo
		dataType: string
		lineageTag: aaaaaaaa-0000-0000-0000-000000000201
		summarizeBy: none
		sourceColumn: dispositivo

		annotation SummarizationSetBy = Automatic

	column hora
		dataType: dateTime
		formatString: General Date
		lineageTag: aaaaaaaa-0000-0000-0000-000000000202
		summarizeBy: none
		sourceColumn: hora

		annotation SummarizationSetBy = Automatic

	column dia
		dataType: dateTime
		formatString: Short Date
		lineageTag: aaaaaaaa-0000-0000-0000-000000000203
		summarizeBy: none
		sourceColumn: dia

		annotation SummarizationSetBy = Automatic

	column co_prom_ppm
		dataType: double
		formatString: 0.0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000204
		summarizeBy: average
		sourceColumn: co_prom_ppm

		annotation SummarizationSetBy = Automatic

	column co_max_ppm
		dataType: double
		formatString: 0.0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000205
		summarizeBy: max
		sourceColumn: co_max_ppm

		annotation SummarizationSetBy = Automatic

	column humedad_prom_pct
		dataType: double
		formatString: 0.0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000206
		summarizeBy: average
		sourceColumn: humedad_prom_pct

		annotation SummarizationSetBy = Automatic

	column humedad_min_pct
		dataType: double
		formatString: 0.0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000207
		summarizeBy: min
		sourceColumn: humedad_min_pct

		annotation SummarizationSetBy = Automatic

	column n_anomalias
		dataType: int64
		formatString: 0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000208
		summarizeBy: sum
		sourceColumn: n_anomalias

		annotation SummarizationSetBy = Automatic

	column n_eventos_riesgo
		dataType: int64
		formatString: 0
		lineageTag: aaaaaaaa-0000-0000-0000-000000000209
		summarizeBy: sum
		sourceColumn: n_eventos_riesgo

		annotation SummarizationSetBy = Automatic

	column nivel_max
		dataType: string
		lineageTag: aaaaaaaa-0000-0000-0000-00000000020a
		summarizeBy: none
		sourceColumn: nivel_max

		annotation SummarizationSetBy = Automatic

	column riesgo_score
		dataType: double
		formatString: 0.0
		lineageTag: aaaaaaaa-0000-0000-0000-00000000020b
		summarizeBy: average
		sourceColumn: riesgo_score

		annotation SummarizationSetBy = Automatic

	partition RiesgoPorHora = m
		mode: import
		source =
				let
					Origen = PostgreSQL.Database("gheslait.com:15432", "timescaledb"),
					Vista = Origen{[Schema="combustion_riesgo", Item="vw_riesgo_por_hora"]}[Data],
					Tipos = Table.TransformColumnTypes(Vista, {{"hora", type datetime}, {"dia", type datetime}})
				in
					Tipos

	annotation PBI_ResultType = Table
